background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
title: Self-Hosted Dashboard
theme: dark
layout: auto
color: indigo
headerStyle: clean
iconStyle: theme
showStats: true
